sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "10.5"

env:
  - CODECOV_TOKEN=da5c4fe1-2616-413d-9823-7ed284da66a5

branches:
  only:
    - develop

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
