version: '3.6'
services:
  app:
    build: .
    command: "npm start"
    ports:
      - "4200:4200"
      - "49153:49153"
    expose:
      - "4200"
      - "49153"
    volumes:
      - "./:/usr/app/"
      - "/usr/app/node_modules"
