version: '3'

services:
  webdev:
    build:
      context: ../../.
      dockerfile: provision/dev/Dockerfile
    command: npm run start
    volumes:
      - ../../.:/app
    ports:
      - "4200:4200"
